# Change these first
owner: ADawidowski # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: WWW
    url: https://oomkill.net
  - name: WebMail
    url: https://mail.oomkill.net/rc
  - name: SMTP
    check: "tcp-ping"
    url: mail.oomkill.net
    port: 465
  - name: IMAPS
    check: "tcp-ping"
    url: mail.oomkill.net
    port: 993
  - name: POP3S
    check: "tcp-ping"
    url: mail.oomkill.net
    port: 995

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /upptime
  #logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: oomkill.net status page
  introTitle: "oomkill.net status page"
  introMessage: oomkill.net status page
  navbar:
    - title: Status
      href: /upptime

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
